### ISSUE TITLE
[alpha.2] Unable to open connection to local database

### ISSUE THREAD

**Issue by juspky** [mastra-ai/mastra#2806]
Hi, I just created a new mastra app using alpha.2.

When I try to run it I get "Unable to open connection to local database"

```
PS D:\Programming\Mastra\mastra-app> npm run dev

> mastra-app@1.0.0 dev
> mastra dev

INFO [2025-03-06 18:58:37.731 +0100] (BUNDLER - Dev): Starting watcher...
INFO [2025-03-06 18:58:38.007 +0100] (BUNDLER - Dev): Bundling finished, starting server...
INFO [2025-03-06 18:58:38.008 +0100] (Mastra CLI): [Mastra Dev] - Starting server...
(node:23316) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
D:\Programming\Mastra\mastra-app\node_modules\libsql\index.js:83
      this.db = databaseOpen(path, authToken, encryptionCipher, encryptionKey);
                ^

Error: ConnectionFailed("Unable to open connection to local database D:\\Programming\\Mastra\\mastra-app\\D:\\Programming\\Mastra\\mastra-app\\.mastra\\mastra.db: 14")
    at new Database (D:\Programming\Mastra\mastra-app\node_modules\libsql\index.js:83:17)
    at _createClient (file:///D:/Programming/Mastra/mastra-app/node_modules/@libsql/client/lib-esm/sqlite3.js:47:16)
    at _createClient (file:///D:/Programming/Mastra/mastra-app/node_modules/@libsql/client/lib-esm/node.js:21:16)
    at createClient (file:///D:/Programming/Mastra/mastra-app/node_modules/@libsql/client/lib-esm/node.js:11:12)
    at new LibSQLStore (file:///D:/Programming/Mastra/mastra-app/node_modules/@mastra/core/dist/chunk-MGBSRQQW.js:20:19)
    at new Mastra (file:///D:/Programming/Mastra/mastra-app/node_modules/@mastra/core/dist/chunk-UFMLHP4G.js:40:17)
    at file:///D:/Programming/Mastra/mastra-app/.mastra/output/index.mjs:257:16
    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:547:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5) {
  code: ''
}

Node.js v22.13.1
```

**Comment by juspky** [comment]
I might have found out why.

According to the error mastra.db should be in `D:\\Programming\\Mastra\\mastra-app\\D:\\Programming\\Mastra\\mastra-app\\.mastra\\mastra.db: 14"`

But it gets created in this folder instead
`D:\Programming\Mastra\mastra.db`

**Comment by TylerBarnes** [comment]
Thanks for the report @juspky ! I merged a fix already - just about to do a new alpha release that includes it

**Comment by juspky** [comment]
epic!

**Comment by trfi** [comment]
> Thanks for the report [@juspky](https://github.com/juspky) ! I merged a fix already - just about to do a new alpha release that includes it

Looking forward to it

**Comment by TylerBarnes** [comment]
It's out! You'll need `mastra@0.2.9-alpha.5` and `@mastra/core@0.5.0-alpha.5`. Gonna close this but comment here if you're seeing any issues and I'll re-open and take a look asap

**Comment by juspky** [comment]
@TylerBarnes 

mastra.db is in the correct folder now. I still get the error `Error: ConnectionFailed("Unable to open connection to local database D:\\Programming\\Mastra\\mastra-app\\D:\\Programming\\Mastra\\mastra-app\\.mastra\\mastra.db: 14")`

It seems odd to me that the path is in there twice in a row.
Is that maybe the cause of the issue?

**Comment by TylerBarnes** [comment]
Yes, that's definitely not right, I'll take a look on my gaming PC 😄

**Comment by juspky** [comment]
The issue is in the rewriteDbUrl(url) function

```ts
  rewriteDbUrl(url) {
    if (url.startsWith("file:") && !url.startsWith("file:/")) {
      const cwd = process.cwd();
      const relativePath = url.slice("file:".length);
      if (cwd.includes(".mastra") && (cwd.endsWith(`output`) || cwd.endsWith(`output/`) || cwd.endsWith(`output\\`))) {
        const baseDir = join(cwd, `..`, `..`);
        console.log({url, baseDir, relativePath})
        const fullPath = join(baseDir, relativePath);
        this.logger.debug(
          `Initializing LibSQL db with url ${url} with relative file path from inside .mastra/output directory. Rewriting relative file url to "file:${fullPath}". This ensures it's outside the .mastra/output directory.`
        );
        return `file:${fullPath}`;
      }
    }
    return url;
  }
```
 
On Windows the joined paths both contain the full path:
``` ts
{
  url: 'file:D:\\Programming\\Mastra\\mastra-app\\.mastra\\mastra.db',
  baseDir: 'D:\\Programming\\Mastra\\mastra-app',
  relativePath: 'D:\\Programming\\Mastra\\mastra-app\\.mastra\\mastra.db'
}
```

**Comment by TylerBarnes** [comment]
I'm looking at doing this right now :
```ts
  protected rewriteDbUrl(url: string): string {
    if (url.startsWith('file:')) {
      const pathPart = url.slice('file:'.length);

      if (isAbsolute(pathPart)) {
        return url;
      }
```

**Comment by juspky** [comment]
The PR solved the issue for me

**Comment by TylerBarnes** [comment]
Thanks @juspky , will get it merged and released in a moment here

**Comment by TylerBarnes** [comment]
Fix is out in `@mastra/core@0.5.0-alpha.6` and `mastra@0.2.9-alpha.6` thanks for helping @juspky !
Will be out on the latest tag soonish, just doing some verification on latest tag on all features before we do a full release
