### ISSUE TITLE
mastra dev / monorepo dependancy bundling.

### ISSUE THREAD

**Issue by PaulieScanlon** [mastra-ai/mastra#5584]
### Describe the Bug

When developing a mono repo using the below project structure, Mastra (apps/api) fails to import / bundle dependacies used by packages/cats

```
apps/
├── api/
├── web/

packages/
├── cats/
├── utils/
```

In my test repo you'll see packages/cats/src/test-cat imports and uses `bcrypt`. In apps/api/src/mastra/agents is where i import and try to use `testCat`.

Running a local build with `pnpm build` works fine.

Running a local dev with `pnpm dev` throws the following error.

```
node:internal/modules/run_main:123
    triggerUncaughtException(
    ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'bcrypt' imported from /Users/paul/Documents/Mastra/development/_tests/_test-pnpm-monorepo/apps/api/.mastra/output/index.mjs
Did you mean to import "bcrypt/bcrypt.js"?
    at packageResolve (node:internal/modules/esm/resolve:873:9)
    at moduleResolve (node:internal/modules/esm/resolve:946:18)
    at defaultResolve (node:internal/modules/esm/resolve:1188:11)
    at nextResolve (node:internal/modules/esm/hooks:864:28)
    at resolve (file:///Users/paul/Documents/Mastra/development/_tests/_test-pnpm-monorepo/node_modules/.pnpm/mastra@0.10.8_@mastra+core@0.10.8_openapi-types@12.1.3_react@19.1.0_zod@3.25.67__@opent_e0a5b657474da9b0eee6b931f6d64e26/node_modules/mastra/dist/commands/dev/telemetry-resolver.js:4:12)
    at nextResolve (node:internal/modules/esm/hooks:864:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:306:30)
    at handleMessage (node:internal/modules/esm/worker:196:24)
    at checkForMessages (node:internal/modules/esm/worker:138:28)
    at process.<anonymous> (node:internal/modules/esm/worker:157:5) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Steps To Reproduce

1. Clone the test repo: https://github.com/PaulieScanlon/_test-pnpm-monorepo
2. run: `pnpm install`
3. run `pnpm build`
4. run `pnpm dev`

### Expected Behavior

running `pnpm dev` should start both the Next.js app (apps/web) and the Mastra API (apps/api)

### Environment Information

- `OPENAI_API_KEY` required in for the Mastra API (apps/api)

### Verification

- [x] I have searched the existing issues to make sure this is not a duplicate
- [x] I have included sufficient information for the team to reproduce and understand the issue

**Comment by nowaythatworked** [comment]
I have a similar issue! Importing package A (resolved via tsconfig paths) which imports another package B from the monorepo, but this fails to be imported. It seems like the tsconfig paths in package A are not being respected. Adding proper entries in the mastra project package does not help either. Completely stuck here.

**Comment by wardpeet** [comment]
@PaulieScanlon the issue with your project is tsconfig paths as well. Not sure why you're using it when you're using workspaces.

**Comment by nowaythatworked** [comment]
@wardpeet the issue is not actually tsconfig paths but that internal dependencies of a dependency are not being transpiled/bundled. If they would be transpiled, tsconfig would be respected and the packages could be resolved. We actually do not install internal packages via `package": "workspace:*`, but use tsconfig paths, for better resolving and other internal reasons. The issue here seems very closely related to  #1996 .

In our case, we have a structure like this:
```
packages/
    core/
    kit/
    mastra-agent/
```

In `mastra-agent` we import from `core`, which in turn can import from `kit`. When importing files from `core`, which do not import from `kit`, everything works fine. Files from `core` are being transpiled & bundled. But as soon as a file also import from `kit` dev & build breaks. I was able to resolve the issue in in the build process by not relying on tsconfig paths, however, files from `kit` where still not transpiled and so the server can not be started, because it fails to resolve.

**Comment by wardpeet** [comment]
@nowaythatworked can you upgrade all mastra related packages to tsconfig-compile tag. That way I can check if https://github.com/mastra-ai/mastra/pull/5641 works for you

**Comment by nowaythatworked** [comment]
@wardpeet first off thank you for replying & handling this so fast! The general resolving of tsconfigpaths seems to work with this version. However I run into another problem which might be (?) related. 
When importing with `import * as X from "relative-path-within-internal-package"` the dev server can't start. This only happens when an import-all is used in an imported internal package (resolved via tsconfigpaths), so I import a file from `@project/package-A` and inside this I have `import * as X from './file'`. When using such import-all statemen directly in the mastra package it works.
These imports result in a bunch of `import 'dependency-in-file'` in the output index.mjs. Some of these imported dependencies are again from an internal package which can not be resolved from node_modules but there are also external dependencies which are used in this internal package like `import @aws-sdk/lib-dynamodb` or `import 'libphonenumber-js'`. 

In short: It seems like using import-all statements in internal packages resolved via tsconfigpaths are still not bundled properly.

If you need any more details just let me know, I am more than happy to help to resolve this!

**Comment by Rounak-stha** [comment]
It seems Mastra supports only native ESM semantics, which means:

- You have to set "type": "module" explicitly in your package.json.
- You must include file extensions in all imports (e.g. .js), no implicit extension resolution.
- Directory imports don’t work — importing from a folder won’t automatically load its index.js.

This is basically how native Node ESM works out of the box, so no bundler magic here.
Because of this, barrel files (re-exports via index.js) require explicit extensions `.js, .ts` in imports during dev, which can be a bit inconvenient.

A improvement could be supporting enhanced module resolution (like automatic extension or directory index resolution) in the dev server.
Just wanted to share this insight in case it helps others understand the current behavior.

**Comment by wardpeet** [comment]
@nowaythatworked i'll chck that out tomoorow

@Rounak-stha thanks you, I believe we fixed, number 1 and number 2.

**Comment by Rounak-stha** [comment]
@wardpeet 
should the shared package in a monorepo with an app consuming mastra be completely bundled with all file extensions explicit in the import path? I created this example monorepo package in this [fork](https://github.com/Rounak-stha/mastra/tree/monorepo-shared-package-bundle-error/examples/monorepo) where the shared package is just built(transpiled) with tsc and consumed by an app using mastra. Since mastra spins up a dev server, I was assuming it would bundle all its dependencies including the workspace dependencies. 

Also, I saw this [commit](https://github.com/mastra-ai/mastra/commit/ec7f824332fb67bb5c1153c283d7376bc15e2c44)  adding a custom plugin to support non extension import, is this somehow related with what we're talking about?

Also noticed that mastra is using rollup and the bundler options in `package/deployer` does not set any externals, so I was assuming everything should be bundled, but that is not the case somehow, which made me super confused. 😓

**Comment by wardpeet** [comment]
Thank you but that is another issue :) That has to do with transpiled packages and esm loading https://github.com/mastra-ai/mastra/issues/1996

**Comment by nowaythatworked** [comment]
Hey @wardpeet I just installed the latest version of mastra, @mastra/core, etc and the issue is still there. Imports from packages which are defined in tsconfig paths, do not get resolved & bundled properly. In the output js file there is simply the same import statement. This is stopping us from integrating Mastra into our platform and we really really want to use mastra. I would really appreicate it if you had another look.

Alternativeley: How about using vite for the dev server? vite has the tsconfigPaths plugin and in general big ecosystem which already handles many edge cases.
