### ISSUE TITLE
[DISCORD:1430237859050422283] VercelDeployer failing to build

### ISSUE THREAD

**Issue by wardpeet** [mastra-ai/mastra#9115]
This issue was created from Discord post: https://discord.com/channels/1309558646228779139/1430237859050422283

```
import { Mastra } from '@mastra/core/mastra';
import { VercelDeployer } from "@mastra/deployer-vercel";

import { udsDesignAgent } from '@/mastra/agents/uds-design.agent';

import { generateComponentWorkflow } from './workflows/generate-component.workflow';

export const mastra = new Mastra({
  bundler: {
    externals: ['ts-node'],
  },
  agents: { udsDesignAgent },
  workflows: { generateComponentWorkflow },
  deployer: new VercelDeployer()

});

```

Output 
```
INFO [2025-10-21 11:52:50.409 -0500] (Mastra CLI): Deployer found, preparing deployer build...
INFO [2025-10-21 11:52:53.844 -0500] (Mastra CLI): Analyzing dependencies...
INFO [2025-10-21 11:52:54.638 -0500] (Mastra CLI): Optimizing dependencies...
INFO [2025-10-21 11:52:59.512 -0500] (Mastra CLI): Bundling Mastra application
ERROR [2025-10-21 11:53:00.608 -0500] (Mastra CLI): Failed during bundler bundle stage: ../../node_modules/fsevents/fsevents.node (1:0): Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
    domain: "DEPLOYER"
    category: "SYSTEM"
    details: {}
error: "mastra" exited with code 1

```

**Comment by roaminro** [comment]
resolved by user

**Comment by paschaldev** [comment]
@wardpeet @roaminro 

What was the solution to this problem? I'm currently experiencing the same thing

<img width="922" height="250" alt="Image" src="https://github.com/user-attachments/assets/4045dd08-94f4-46da-bb16-1fae20952a75" />
<img width="708" height="160" alt="Image" src="https://github.com/user-attachments/assets/47f31f04-b874-4803-829d-669adc626409" />
<img width="919" height="42" alt="Image" src="https://github.com/user-attachments/assets/8e3351b0-c483-4f84-86e4-8b5f67b98b14" />
<img width="413" height="118" alt="Image" src="https://github.com/user-attachments/assets/55bf46a0-9ef4-4bfb-a425-77157a79ca5a" />

**Comment by paschaldev** [comment]
For anyone reading this...

TLDR; Update tsconfig, set `verbatimModuleSyntax` to `false` to fix this error.

In my case, this issue was acuased by the tsconfig file. The `verbatimModuleSyntax` when it's `true`. Setting it to false fixes the build. I also didn't have to set any property in `externals`, when I did, build still failed.

<img width="330" height="104" alt="Image" src="https://github.com/user-attachments/assets/c042f469-f622-4c74-91c4-b96eee8f74ed" />
<img width="292" height="53" alt="Image" src="https://github.com/user-attachments/assets/2354b5ed-60f6-4699-bc88-fc04e7601f8b" />
